pre:
  parts:
    xmbshell:
      stage-packages:
      - libavformat60
      - libavcodec60
      - libavutil58
      - libavfilter9
      - libswscale7
      - libswresample4
      - libpostproc57
      - libavdevice60
  plugs:
    ffmpeg-2404: null
  apps:
    xmbshell:
      environment:
        LD_LIBRARY_PATH: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH
        PATH: null
