variables:
  - &minio-settings
    access_key:
      from_secret: minio_access_key
    secret_key:
      from_secret: minio_secret_key
    endpoint:
      from_secret: minio_endpoint
    path_style: true
    region: eu-central-jcm

when:
  - event: push
  - event: manual

labels:
  compat: riscv64
  gpu: BXE-4-32

steps:
  build:
    image: ubuntu:plucky
    commands:
      - UBUNTU_VERSION=plucky
      - apt-get update
      - >-
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
        curl clang-20 clang-tools-20 cmake ninja-build git glslang-tools xxd patch curl gettext ca-certificates libglib2.0-bin imagemagick
        libvulkan-dev pkg-config libsystemd-dev libsdl2-dev libsdl2-mixer-dev libsdl2-image-dev libglm-dev
        libspdlog-dev libfreetype-dev libglibmm-2.4-dev libsdbus-c++-dev libboost-dev
        libavformat-dev libavcodec-dev libavutil-dev libavfilter-dev
        libswscale-dev libswresample-dev libpostproc-dev libavdevice-dev
      - .woodpecker/download_unlicensed.sh
      - BUILD_VERSION=$(git describe --tags --always)
      - >-
        cmake -B build -G Ninja
        -DCMAKE_C_COMPILER=clang-20 -DCMAKE_CXX_COMPILER=clang++-20
        -DCMAKE_BUILD_TYPE=Debug -DBUILD_VERSION=$BUILD_VERSION
      - cmake --build build --parallel 3
      - glib-compile-schemas schemas
      # Install it (and upload it for debugging)
      - cd build/
      - mkdir -p upload/build upload/beta
      - DESTDIR=install cmake --install . --prefix /usr
      - tar -vcaf upload/build/xmbshell-$BUILD_VERSION-$UBUNTU_VERSION-$(arch).tar.gz -C install .
      - cp upload/build/xmbshell-$BUILD_VERSION-$UBUNTU_VERSION-$(arch).tar.gz upload/beta/xmbshell-beta-$UBUNTU_VERSION-$(arch).tar.gz
  build-upload-build:
    image: git.jcm.re/jcm/woodpecker-plugin-s3:latest-riscv64
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/upload/build/*
      strip_prefix: build/upload/build/
      target: /artifacts/${CI_REPO}/${CI_PIPELINE_NUMBER}/public/
  build-upload-branch:
    image: git.jcm.re/jcm/woodpecker-plugin-s3:latest-riscv64
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/upload/beta/*
      strip_prefix: build/upload/beta/
      target: /artifacts/${CI_REPO}/${CI_COMMIT_BRANCH}/public/
      overwrite: true
  test:
    image: ubuntu:plucky
    commands:
      - apt-get update
      - >-
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends
        dbus-x11 mesa-vulkan-drivers curl ca-certificates libdrm2
        libsdl2-2.0-0 libsdl2-mixer-2.0-0 libsdl2-image-2.0-0
        libglibmm-2.4-1t64 libsdbus-c++2
        libavformat61 libavcodec61 libavutil59 libavfilter10 libswscale8 libswresample5 libpostproc58 libavdevice61
        vulkan-validationlayers ffmpeg fonts-ubuntu
      - >
        curl -L https://github.com/starfive-tech/soft_3rdpart/raw/refs/heads/JH7110_VisionFive2_devel/IMG_GPU/out/img-gpu-powervr-bin-1.19.6345021.tar.gz
        | tar -x -z -v -C / --strip-components=2 --keep-directory-symlink img-gpu-powervr-bin-1.19.6345021/target
        && rm /usr/lib/libvulkan.so*
      - DREAMRENDER_DEVICE_NAME="PowerVR B-Series BXE-4-32" ./test/headless.sh
    volumes:
      - /dev/dri/renderD128:/dev/dri/renderD128
    privileged: true
  test-upload:
    image: git.jcm.re/jcm/woodpecker-plugin-s3:latest-riscv64
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/test-*
      strip_prefix: build/
      target: /artifacts/${CI_REPO}/${CI_PIPELINE_NUMBER}/public/
    when:
      - status: [ success, failure ]
  test-upload-branch:
    image: git.jcm.re/jcm/woodpecker-plugin-s3:latest-riscv64
    settings:
      <<: *minio-settings
      bucket: woodpecker
      source: build/test-output.*
      strip_prefix: build/
      target: /artifacts/${CI_REPO}/${CI_COMMIT_BRANCH}/public/
      overwrite: true
