name: xmbshell
version: "1.0"
title: xmbshell
summary: A desktop shell mimicing the look and functionality of the XrossMediaBar.
icon: icons/xmbshell.png
contact: jcm@jcm.re
source-code: https://github.com/JnCrMx/xmbshell
website: https://github.com/JnCrMx/xmbshell
description: |
  A desktop shell mimicing the look and functionality of the XrossMediaBar.

  Features:
  - Awesome XMB background wave
  - Basic file management
  - Launch other apps

package-repositories:
- architectures:
  - amd64
  components:
  - main
  formats:
  - deb
  key-id: 6084F3CF814B57C1CF12EFD515CF4D18AF4F7421
  suites:
  - llvm-toolchain-noble-19
  type: apt
  url: http://apt.llvm.org/noble/

base: core24
confinement: strict
parts:
  xmbshell:
    plugin: cmake
    source-type: local
    source: .
    build-snaps:
      - ffmpeg-2404-sdk
      - mesa-2404
    build-packages:
      - git
      - clang-19
      - clang-tools-19
      - ninja-build
      - glslang-tools
      - libvulkan-dev
      - libglm-dev
      - libspdlog-dev
      - libfreetype-dev
      - libglibmm-2.68-dev
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libpulse-dev
    stage-packages:
      - libfreetype6
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-mixer-2.0-0
      - libspdlog1.12-fmt9
      - libglibmm-2.68-1t64
      - libpulse0
      - fonts-ubuntu
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_CXX_COMPILER=/usr/bin/clang++-19"
      - "-DCMAKE_C_COMPILER=/usr/bin/clang-19"
      - "-DCMAKE_EXE_LINKER_FLAGS=-Wl,--unresolved-symbols=ignore-in-shared-libs"
      - "-GNinja"
    build-environment:
      - CMAKE_PREFIX_PATH: ${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/cmake${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
      - PKG_CONFIG_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
      - LD_LIBRARY_PATH: /snap/ffmpeg-2404-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PATH: /snap/ffmpeg-2404-sdk/current/usr/bin${PATH:+:$PATH}
  gpu-2404:
    after: [xmbshell]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after: [xmbshell]
    plugin: nil
    build-snaps: [core24, gtk-common-themes, gnome-46-2404]
    override-prime: |
      set -eux
      for snap in "core24" "gtk-common-themes" "gnome-46-2404"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done
layout:
  $SNAP/usr/share/xmbshell/Ubuntu-R.ttf:
    symlink: $SNAP/usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf
# slots:
#   dbus-svc:
#     interface: dbus
#     bus: session
#     name: re.jcm.xmbos.xmbshell
plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  ffmpeg-2404:
    interface: content
    target: ffmpeg-platform
    default-provider: ffmpeg-2404
apps:
  xmbshell:
    command: usr/bin/xmbshell
    command-chain:
      - bin/gpu-2404-wrapper
    desktop: usr/share/applications/xmbshell.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH
      PATH: $SNAP/ffmpeg-platform/usr/bin:$PATH
    # slots:
    #   - dbus-svc
    extensions:
      - gnome
    plugs:
      - network
      - home
      - gsettings
      - joystick
      - audio-playback
